name: wasmd
description: An exploration of compiling Wasm to Dart. 
version: 0.1.0
repository: https://github.com/devoncarew/wasmd

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.3.0
  charcode: ^1.3.0
  code_builder: ^4.4.0
  collection: ^1.17.0
  dart_style: ^2.2.0
  logging: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  benchmark_harness: ^2.2.0
  cli_util: ^0.3.0
  lints: ^2.0.0
  meta: ^1.8.0
  test: ^1.22.0
