name: Dart CI

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: dev

      - name: Install dependencies
        run: dart pub get

      - name: Show generated file sizes
        run: |
          echo "File sizes in KB"
          echo ""
          ls -skS -1 -R test/spec/**/*.dart
          ls -skS -1 -R samples/*.dart

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed bin/ lib/ tool/

      - name: Analyze project source
        # run: dart analyze --fatal-infos
        run: dart analyze

      # TODO: verify that the generators work (regen, spec)

      - name: Run tests
        run: dart tool/tests.dart
